In [3]:
pip install pandas numpy matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (2.4.6)
Requirement already satisfied: matplotlib in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (3.10.9)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('../data/raw/imdb_movies.csv')
df.head()

,movie_id,title,genre,rating,budget_million,gross_million,director,lead_actor,release_year
0,1.0,Movie 1,Thriller,4.2,100.0,NaN,Cameron,NaN,2017.0
1,2.0,Movie 2,Sci-Fi,7.8,150.0,150.0,Nolan,Actor B,2019.0
2,3.0,Movie 3,Thriller,4.9,30.0,600.0,Spielberg,Actor D,2016.0
3,4.0,Movie 4,Thriller,9.1,100.0,600.0,Rajamouli,Actor D,2015.0
4,5.0,Movie 5,Sci-Fi,4.5,10.0,600.0,Cameron,Actor C,2022.0

In [6]:
df.shape

(5500, 9)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_id        5177 non-null   float64
 1   title           5500 non-null   str
 2   genre           5500 non-null   str
 3   rating          5211 non-null   float64
 4   budget_million  4569 non-null   float64
 5   gross_million   4583 non-null   float64
 6   director        4720 non-null   str
 7   lead_actor      4586 non-null   str
 8   release_year    4886 non-null   float64
dtypes: float64(5), str(4)
memory usage: 386.8 KB

In [8]:
df.describe()

          movie_id      rating  budget_million  gross_million  release_year
count  5177.000000  5211.00000     4569.000000    4583.000000   4886.000000
mean   2750.281630     6.50641       69.072007     229.426140   2018.492223
std    1588.028767     1.73132       49.589526     207.825825      2.296863
min       1.000000     3.50000       10.000000      20.000000   2015.000000
25%    1375.000000     5.00000       30.000000      80.000000   2016.000000
50%    2750.000000     6.50000       60.000000     150.000000   2018.000000
75%    4125.000000     8.00000      100.000000     300.000000   2021.000000
max    5500.000000     9.50000      150.000000     600.000000   2022.000000

In [9]:
df.isnull().sum()

movie_id          323
title               0
genre               0
rating            289
budget_million    931
gross_million     917
director          780
lead_actor        914
release_year      614
dtype: int64