In [1]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
df = pd.read_csv('../data/clean/imdb_movies_clean.csv')
df.head()

,movie_id,title,genre,rating,budget_million,gross_million,director,lead_actor,release_year
0,1430.0,Movie 1430,Thriller,9.5,30.0,600.0,Rajamouli,Actor D,2018.0
1,1603.0,Movie 1603,Comedy,9.5,100.0,600.0,Cameron,Actor D,2017.0
2,1892.0,Movie 1892,Action,9.5,100.0,600.0,Rajamouli,Actor A,NaN
3,2658.0,Movie 2658,Action,9.5,100.0,600.0,Unknown,Unknown,2020.0
4,3928.0,Movie 3928,Romance,9.5,10.0,600.0,Tarantino,Actor A,NaN

In [9]:
engine = create_engine(
    "mysql+pymysql://root:admin%40123@localhost/imdb_etl"
)

In [10]:
df.to_sql(
    name='imdb_movies',
    con=engine,
    if_exists='append',
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully

Validation Queries

Total Records

In [11]:
query = "SELECT COUNT(*) AS total_records FROM imdb_movies"

pd.read_sql(query, engine)

   total_records
0           5473

Check Movie ID Nulls

In [14]:
query = " SELECT COUNT(*) AS missing_movie_id FROM imdb_movies WHERE movie_id IS NULL "
pd.read_sql(query, engine)

   missing_movie_id
0                 0

Check Rating Nulls

In [17]:
query = " SELECT COUNT(*) AS missing_rating FROM imdb_movies WHERE rating IS NULL"

pd.read_sql(query, engine)

   missing_rating
0               0

View Sample Data

In [18]:
query = "SELECT * FROM imdb_movies LIMIT 10"

pd.read_sql(query, engine)

,movie_id,title,genre,rating,budget_million,gross_million,director,lead_actor,release_year
0,1,Movie 1,Thriller,4.2,100.0,NaN,Cameron,Unknown,2017
1,2,Movie 2,Sci-Fi,7.8,150.0,150.0,Nolan,Actor B,2019
2,3,Movie 3,Thriller,4.9,30.0,600.0,Spielberg,Actor D,2016
3,4,Movie 4,Thriller,9.1,100.0,600.0,Rajamouli,Actor D,2015
4,5,Movie 5,Sci-Fi,4.5,10.0,600.0,Cameron,Actor C,2022
5,6,Movie 6,Romance,7.2,NaN,600.0,Scorsese,Actor C,2019
6,7,Movie 7,Horror,8.5,30.0,NaN,Unknown,Actor D,2017
7,8,Movie 8,Comedy,7.8,60.0,20.0,Spielberg,Actor B,2018
8,9,Movie 9,Romance,8.3,NaN,20.0,Cameron,Actor A,2018
9,10,Movie 10,Sci-Fi,5.0,NaN,20.0,Spielberg,Actor B,2019